export const paginationFilterableKey = [
  "type",
  "searchTerm",
  "firstName",
  "lastName",
  "email",
  "holocaustSurvivor",
  "dateOfBirth",
  "address",
  "apartment",
  "city",
  "state",
  "zipCode",
  "peopleHousehold",
  "dietaryRestrictions",
  "deliveryInstructions",
  "clientDeliveryGroup",
];

export const TransportVolunteerSearchTermsFields = [
  "firstName",
  "lastName",
  "email",
  // "holocaustSurvivor",
  "dateOfBirth",
  "address",
  "apartment",
  "city",
  "state",
  "zipCode",
  "peopleHousehold",
  "dietaryRestrictions",
  "deliveryInstructions",
  "clientDeliveryGroup",
];
